project:  
  output-dir: output/book/
book:
  chapters: 
    - index.qmd
    - skript/introduction_en.qmd
    - skript/array_creation_en.qmd
    - skript/array_info_en.qmd
    - skript/array_calculation_en.qmd
    - skript/array_slicing_en.qmd
    - skript/array_manipulation_en.qmd
    - skript/array_read_n_write_en.qmd
    - skript/array_images_en.qmd
    - skript/assessment_en.qmd
    
    - uebungen/uebung.qmd
    - klausurfragen/klausurfragen_en.qmd