project:  
  output-dir: output/book/
book:
  chapters: 
    - index.qmd
    - skript/introduction.qmd
    - skript/array_creation.qmd
    - skript/array_info.qmd
    - skript/array_calculation.qmd
    - skript/array_slicing.qmd
    - skript/array_manipulation.qmd
    - skript/array_read_n_write.qmd
    - skript/array_images.qmd
    - skript/assessment.qmd
    
    - uebungen/uebung.qmd
    - klausurfragen/klausurfragen.qmd